services:
  ai-security-logger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-security-logger
    restart: unless-stopped
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL_ID=${OPENROUTER_MODEL_ID:-openai/gpt-3.5-turbo}
      - LOG_SOURCES=/app/data/logs
      - PROCESSING_INTERVAL=60
      - SENSITIVITY_KEYWORDS=error,failed,denied,warning,critical,unauthorized,attack,breach,malware,virus
      - DB_PATH=/app/data/db/threats.db
      - OUTPUT_LOG_DIR=/app/reports
    volumes:
      # Mount log sources (adjust paths as needed for your server)
      - /var/log:/host/var/log:ro
      - ./data/logs:/app/data/logs
      - ./data/db:/app/data/db
      - ./reports:/app/reports
      - ./config:/app/config
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - ai-logger-network
    depends_on:
      - redis
    
  redis:
    image: redis:7-alpine
    container_name: ai-logger-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - ai-logger-network
    ports:
      - "6379:6379"

  # Optional: Simple web interface for viewing reports
  nginx:
    image: nginx:alpine
    container_name: ai-logger-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./reports:/usr/share/nginx/html/reports:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - ai-logger-network
    depends_on:
      - ai-security-logger

volumes:
  redis_data:

networks:
  ai-logger-network:
    driver: bridge
